// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopGiay.Data;

#nullable disable

namespace ShopGiay.Migrations
{
    [DbContext(typeof(ShopGiayContext))]
    partial class ShopGiayContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShopGiay.Models.ChiTietGiay", b =>
                {
                    b.Property<int>("MaGiay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiay"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KichCo")
                        .HasColumnType("int");

                    b.Property<int?>("LoaiGiayMaLoai")
                        .HasColumnType("int");

                    b.Property<int>("MaLoaiGiay")
                        .HasColumnType("int");

                    b.Property<string>("MauSac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenGiay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaGiay");

                    b.HasIndex("LoaiGiayMaLoai");

                    b.ToTable("ChiTietGiay");
                });

            modelBuilder.Entity("ShopGiay.Models.LoaiGiay", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoai");

                    b.ToTable("LoaiGiay");
                });

            modelBuilder.Entity("ShopGiay.Models.ChiTietGiay", b =>
                {
                    b.HasOne("ShopGiay.Models.LoaiGiay", "LoaiGiay")
                        .WithMany()
                        .HasForeignKey("LoaiGiayMaLoai");

                    b.Navigation("LoaiGiay");
                });
#pragma warning restore 612, 618
        }
    }
}
